# Generated by Django 4.2.2 on 2023-08-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_tag_post_author_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email_address',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
